# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'data/'
checkpoint_dir: 'saved/'
generated_text_dir: 'generated/'

# training settings
epochs: -1
train_batch_size: 2
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 3
grad_clip: 1.0

# evaluation settings
metrics: ["bleu"]
n_grams: [1,2,3,4,5]
eval_batch_size: 2

